= Sol-1 Homebrew Minicomputer

Sol-1 is a homebrew CPU and Minicomputer built from 74HC logic.

== Features
==== Hardware
* User and Kernel priviledge modes, with up to 256 processes running in parallel.
* Paged virtual memory, such that each process can have a total of 64KB RAM for itself.
* Two serial ports (16550), a real time clock(M48T02), 2 parallel ports(8255), a programmable timer(8253), an IDE hard-drive interface(2.5 Inch HDD), and a soundboard(AY-3-8910).
* 8 prioritized external interrupts
* DMA channel
* The sequencer is microcoded, with 15 ROMS operating horizontally
* 8/16-Bit MUL and DIV instructions
* Fast indexed string instructions in the spirit of x86's REP MOVSB, CMPSB, LODSB, STOSB, etc

==== Software
* Unix like baby operating system (in progress and very early)
* C compiler that generates a Sol-1 assembly output file
  (The output assembly is then assembled separately.)
* SystemVerilog model

https://www.youtube.com/@PauloConstantino167/videos[Video demonstrations here]
